services:
  sb-b-app-wh-$@{SERVICE_SUFFIX}:
    image: ivandrozda/sb-b-app-webhooks:latest
    container_name: sb_b_app_wh_$@{SB_APP_URL_PATH}
    restart: unless-stopped
    environment:
      - QUARKUS_DATASOURCE_DB_KIND=mysql
      - QUARKUS_DATASOURCE_USERNAME=${SB_APP_MYSQL_USER}
      - QUARKUS_DATASOURCE_PASSWORD=${SB_APP_MYSQL_PASSWORD}
      - QUARKUS_DATASOURCE_JDBC_MAX_SIZE=5
      - QUARKUS_DATASOURCE_JDBC_URL=JDBC:MYSQL://${SB_APP_MYSQL_HOST}:3306/$@{SB_NEW_WH_DATABASE_NAME}
      - QUARKUS_HIBERNATE-ORM_DATABASE_GENERATION=create
      - QUARKUS_HTTP_PORT=8080
      - QUARKUS_LOG_CONSOLE_DARKEN=10
      - QUARKUS_INFO_ENABLED=TRUE
      - QUARKUS_MICROMETER_EXPORT_PROMETHEUS_ENABLED=true
      - QUARKUS_MICROMETER_EXPORT_PROMETHEUS_PATH=/metrics
      - MP_METRICS_ENABLED=true
    volumes:
      - /mnt/volume_20gb/sb_b_app_wh_$@{SB_APP_URL_PATH}:/opt/external_data
    networks:
      - sb_network

networks:
  sb_network:
    external: true
