services:
  sb-clients-back-app:
    image: ivandrozda/dti-sb-clients-back:latest
    container_name: sb_clients_back_app
    restart: unless-stopped
    ports:
      - "7854:8080"
    environment:
      - QUARKUS_DATASOURCE_WEBHOOKS_DB_KIND=mysql
      - QUARKUS_DATASOURCE_WEBHOOKS_USERNAME=${SB_WEBHOOKS_MYSQL_USER}
      - QUARKUS_DATASOURCE_WEBHOOKS_PASSWORD=${SB_WEBHOOKS_MYSQL_PASSWORD}
      - QUARKUS_DATASOURCE_WEBHOOKS_JDBC_URL=JDBC:MYSQL://sb_webhooks_sql:3306/SB

      - QUARKUS_DATASOURCE_CLIENTS_BACK_DB_KIND=mysql
      - QUARKUS_DATASOURCE_CLIENTS_BACK_USERNAME=${SB_CLIENTS_BACK_MYSQL_USER}
      - QUARKUS_DATASOURCE_CLIENTS_BACK_PASSWORD=${SB_CLIENTS_BACK_MYSQL_PASSWORD}
      - QUARKUS_DATASOURCE_CLIENTS_BACK_JDBC_URL=JDBC:MYSQL://sb_clients_back_mysql:3306/CLIENTS_BACK

      - QUARKUS_HIBERNATE_ORM_DATABASE_GENERATION=none
      - QUARKUS_HTTP_PORT=8080
      - QUARKUS_LOG_CONSOLE_DARKEN=10
      - QUARKUS_INFO_ENABLED=TRUE
      - QUARKUS_MICROMETER_EXPORT_PROMETHEUS_ENABLED=true
      - QUARKUS_MICROMETER_EXPORT_PROMETHEUS_PATH=/metrics
      - MP_METRICS_ENABLED=true
    networks:
      - sb_network

networks:
  sb_network:
    external: true