services:
  sb-b-app-$@{SERVICE_SUFFIX}:
    image: ivandrozda/sb-b-app:latest
    container_name: sb_b_app_$@{SB_CUSTOMER_NAME}
    restart: unless-stopped
    environment:
      - QUARKUS_DATASOURCE_WEBHOOKS_DB_KIND=mysql
      - QUARKUS_DATASOURCE_WEBHOOKS_USERNAME=${SB_WH_SQL_USER}
      - QUARKUS_DATASOURCE_WEBHOOKS_PASSWORD=${SB_WH_SQL_PASSWORD}
      - QUARKUS_DATASOURCE_WEBHOOKS_JDBC_MAX_SIZE=5
      - QUARKUS_DATASOURCE_WEBHOOKS_JDBC_URL=JDBC:MYSQL://${SB_WH_SQL_HOST}:3306/$@{SB_WH_DATABASE_NAME}
      - QUARKUS_HIBERNATE_ORM_WEBHOOKS_PACKAGES=dti.crmsis.back.dao.wh
      - QUARKUS_HIBERNATE_ORM_DATABASE_WEBHOOKS_GENERATION=update

      - QUARKUS_DATASOURCE_DB_KIND=mysql
      - QUARKUS_DATASOURCE_USERNAME=${SB_PD_SQL_USER}
      - QUARKUS_DATASOURCE_PASSWORD=${SB_PD_SQL_PASSWORD}
      - QUARKUS_DATASOURCE_JDBC_MAX_SIZE=10
      - QUARKUS_DATASOURCE_JDBC_URL=JDBC:MYSQL://${SB_PD_SQL_HOST}:3306/$@{SB_PD_DATABASE_NAME}
      - QUARKUS_HIBERNATE_ORM_PACKAGES=dti.crmsis.back.dao.pd
      - QUARKUS_HIBERNATE_ORM_GENERATION=update
        
      - QUARKUS_DATASOURCE_APP_DB_KIND=mysql
      - QUARKUS_DATASOURCE_APP_USERNAME=${SB_APP_SQL_USER}
      - QUARKUS_DATASOURCE_APP_PASSWORD=${SB_APP_SQL_PASSWORD}
      - QUARKUS_DATASOURCE_APP_JDBC_MAX_SIZE=10
      - QUARKUS_DATASOURCE_APP_JDBC_URL=JDBC:MYSQL://${SB_APP_SQL_HOST}:3306/$@{SB_APP_DATABASE_NAME}
      - QUARKUS_HIBERNATE_ORM_APP_PACKAGES=dti.crmsis.back.dao.app
      - QUARKUS_HIBERNATE_ORM_DATABASE_APP_GENERATION=update

      - QUARKUS_HIBERNATE_ORM_DATABASE_GENERATION=create
      - QUARKUS_HTTP_PORT=8080
      - QUARKUS_LOG_CONSOLE_DARKEN=10
      - QUARKUS_INFO_ENABLED=TRUE
      - QUARKUS_MICROMETER_EXPORT_PROMETHEUS_ENABLED=true
      - QUARKUS_MICROMETER_EXPORT_PROMETHEUS_PATH=/metrics
      - MP_METRICS_ENABLED=true
      - QUARKUS_TRANSACTION_MANAGER_DEFAULT_TRANSACTION_TIMEOUT=600
      - URL_FOR_WEBHOOKS=${URL_FOR_WEBHOOKS}
      - APP_TOKEN=${SB_APP_$@{SB_UPPER_CUSTOMER_NAME}_TOKEN}
      - CUSTOMER_FULL_NAME=$@{CUSTOMER_FULL_NAME}
      - CUSTOMER_NAME=$@{CUSTOMER_NAME}
      - CUSTOMER_PIPEDRIVE_URL=$@{CUSTOMER_PIPEDRIVE_URL}
    networks:
      - sb_network
    volumes:
      - /mnt/docker_data/sb_b_app_$@{SB_CUSTOMER_NAME}/external_data:/opt/external_data
    deploy:
      resources:
        limits:
          cpus: '0.70'
          memory: 1G

networks:
  sb_network:
    external: true