services:
  sb-b-webhooks-app:
    image: ivandrozda/sb-b-webhooks-app:latest
    container_name: sb_b_webhooks_app
    restart: unless-stopped
    environment:
      - QUARKUS_DATASOURCE_DB_KIND=mysql
      - QUARKUS_DATASOURCE_USERNAME=${SB_APP_MYSQL_USER}
      - QUARKUS_DATASOURCE_PASSWORD=${SB_APP_MYSQL_PASSWORD}
      - QUARKUS_DATASOURCE_JDBC_URL=JDBC:MYSQL://${SB_APP_MYSQL_HOST}:3306/SB_APP
      - QUARKUS_HIBERNATE-ORM_DATABASE_GENERATION=none
      - QUARKUS_HTTP_PORT=8080
      - QUARKUS_LOG_CONSOLE_DARKEN=10
      - QUARKUS_INFO_ENABLED = TRUE
      - QUARKUS_MICROMETER_EXPORT_PROMETHEUS_ENABLED=true
      - QUARKUS_MICROMETER_EXPORT_PROMETHEUS_PATH=/metrics
      - MP_METRICS_ENABLED=true
    networks:
      - sb_network

networks:
  sb_network:
    external: true
