services:
  sb-b-sql-webhooks:
    image: mysql:8.0
    container_name: sb_b_sql_webhooks
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: ${SB_APP_MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: SB_APP
      MYSQL_USER: ${SB_APP_MYSQL_USER}
      MYSQL_PASSWORD: ${SB_APP_MYSQL_PASSWORD}
      MYSQL_ALLOW_EMPTY_PASSWORD: yes
    networks:
      - sb_network
    volumes:
      - ./config/scripts/sb_app.sql:/docker-entrypoint-initdb.d/init.sql
      - /mnt/volume_5gb/mysql:/var/lib/mysql
#      - ./sb_app.sql:/docker-entrypoint-initdb.d/init.sql
#      sql:
    ports:
      - "${SB_APP_MYSQL_PORT}:3306"

networks:
  sb_network:
    external: true