services:
  sb-b-sql-all_in_one:
    image: mysql:8.0
    container_name: sb_b_sql_all_in_one
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: ${SB_DEFAULT_SQL_ROOT_PASSWORD}
      MYSQL_DATABASE: SB_DEFAULT
      MYSQL_USER: ${SB_DEFAULT_SQL_USER}
      MYSQL_PASSWORD: ${SB_DEFAULT_SQL_PASSWORD}
      MYSQL_ALLOW_EMPTY_PASSWORD: yes
    networks:
      - sb_network
    volumes:
      - ../config/scripts/all_in_one.sql:/docker-entrypoint-initdb.d/init.sql
      - ../config/mysql/my.cnf:/etc/mysql/my.cnf
      - /mnt/docker_data/sb_b_sql_all_in_one/external_data:/opt/external_data
      - /mnt/docker_data/sb_b_sql_all_in_one/mysql:/var/lib/mysql
#      sql:
    ports:
      - "${SB_DEFAULT_SQL_PORT}:3306"
    deploy:
      resources:
        limits:
          cpus: '0.50'
          memory: 1G
        reservations:
          cpus: '0.25'
          memory: 512M

networks:
  sb_network:
    external: true