package dti.crmsis.back.clients.openapi.v1.api;

import java.util.List;
import java.util.Map;


import dti.crmsis.back.clients.openapi.v1.model.AddActivityTypeRequest;
import dti.crmsis.back.clients.openapi.v1.model.DeleteActivityTypesResponse;
import dti.crmsis.back.clients.openapi.v1.model.GetActivityTypesResponse;
import dti.crmsis.back.clients.openapi.v1.model.UpdateActivityTypeRequest;
import dti.crmsis.back.clients.openapi.v1.model.UpsertActivityTypeResponse;
/**
  * Pipedrive API v1
  * <p>No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)</p>
  */
@jakarta.ws.rs.Path("/activityTypes")
@io.quarkiverse.openapi.generator.annotations.GeneratedClass(value="openapi.yaml", tag = "ActivityTypes")
@jakarta.enterprise.context.ApplicationScoped
public interface ActivityTypesApi {

     /**
     * Add new activity type
     *
     * Adds a new activity type.
     *
     * @param addActivityTypeRequest 
     */
    @io.quarkiverse.openapi.generator.markers.OperationMarker(name="api_key", openApiSpecId="openapi_yaml", operationId="addActivityType", method="POST", path="/v1/activityTypes")
    @io.quarkiverse.openapi.generator.markers.OperationMarker(name="oauth2", openApiSpecId="openapi_yaml", operationId="addActivityType", method="POST", path="/v1/activityTypes")
    @jakarta.ws.rs.POST
    @jakarta.ws.rs.Consumes({"application/json"})
    @jakarta.ws.rs.Produces({"application/json"})
    @io.quarkiverse.openapi.generator.annotations.GeneratedMethod("addActivityType")
    public UpsertActivityTypeResponse addActivityType(
        AddActivityTypeRequest addActivityTypeRequest
    );

     /**
     * Delete an activity type
     *
     * Marks an activity type as deleted.
     *
     * @param id The ID of the activity type
     */
    @io.quarkiverse.openapi.generator.markers.OperationMarker(name="api_key", openApiSpecId="openapi_yaml", operationId="deleteActivityType", method="DELETE", path="/v1/activityTypes/{id}")
    @io.quarkiverse.openapi.generator.markers.OperationMarker(name="oauth2", openApiSpecId="openapi_yaml", operationId="deleteActivityType", method="DELETE", path="/v1/activityTypes/{id}")
    @jakarta.ws.rs.DELETE
    @jakarta.ws.rs.Path("/{id}")
    @jakarta.ws.rs.Produces({"application/json"})
    @io.quarkiverse.openapi.generator.annotations.GeneratedMethod("deleteActivityType")
    public UpsertActivityTypeResponse deleteActivityType(
        @io.quarkiverse.openapi.generator.annotations.GeneratedParam("id") @jakarta.ws.rs.PathParam("id")Integer id
    );

     /**
     * Delete multiple activity types in bulk
     *
     * Marks multiple activity types as deleted.
     *
     * @param ids The comma-separated activity type IDs
     */
    @io.quarkiverse.openapi.generator.markers.OperationMarker(name="api_key", openApiSpecId="openapi_yaml", operationId="deleteActivityTypes", method="DELETE", path="/v1/activityTypes")
    @io.quarkiverse.openapi.generator.markers.OperationMarker(name="oauth2", openApiSpecId="openapi_yaml", operationId="deleteActivityTypes", method="DELETE", path="/v1/activityTypes")
    @jakarta.ws.rs.DELETE
    @jakarta.ws.rs.Produces({"application/json"})
    @io.quarkiverse.openapi.generator.annotations.GeneratedMethod("deleteActivityTypes")
    public DeleteActivityTypesResponse deleteActivityTypes(
        @io.quarkiverse.openapi.generator.annotations.GeneratedParam("ids") @jakarta.ws.rs.QueryParam("ids") String ids
    );

     /**
     * Get all activity types
     *
     * Returns all activity types.
     *
     */
    @io.quarkiverse.openapi.generator.markers.OperationMarker(name="api_key", openApiSpecId="openapi_yaml", operationId="getActivityTypes", method="GET", path="/v1/activityTypes")
    @io.quarkiverse.openapi.generator.markers.OperationMarker(name="oauth2", openApiSpecId="openapi_yaml", operationId="getActivityTypes", method="GET", path="/v1/activityTypes")
    @jakarta.ws.rs.GET
    @jakarta.ws.rs.Produces({"application/json"})
    @io.quarkiverse.openapi.generator.annotations.GeneratedMethod("getActivityTypes")
    public GetActivityTypesResponse getActivityTypes(
    );

     /**
     * Update an activity type
     *
     * Updates an activity type.
     *
     * @param id The ID of the activity type
     * @param updateActivityTypeRequest 
     */
    @io.quarkiverse.openapi.generator.markers.OperationMarker(name="api_key", openApiSpecId="openapi_yaml", operationId="updateActivityType", method="PUT", path="/v1/activityTypes/{id}")
    @io.quarkiverse.openapi.generator.markers.OperationMarker(name="oauth2", openApiSpecId="openapi_yaml", operationId="updateActivityType", method="PUT", path="/v1/activityTypes/{id}")
    @jakarta.ws.rs.PUT
    @jakarta.ws.rs.Path("/{id}")
    @jakarta.ws.rs.Consumes({"application/json"})
    @jakarta.ws.rs.Produces({"application/json"})
    @io.quarkiverse.openapi.generator.annotations.GeneratedMethod("updateActivityType")
    public UpsertActivityTypeResponse updateActivityType(
        @io.quarkiverse.openapi.generator.annotations.GeneratedParam("id") @jakarta.ws.rs.PathParam("id")Integer id, 
        UpdateActivityTypeRequest updateActivityTypeRequest
    );

}