package dti.crmsis.back.clients.openapi.v1.api;

import java.util.List;
import java.util.Map;


import dti.crmsis.back.clients.openapi.v1.model.GetSubscriptionAddonsResponse;
/**
  * Pipedrive API v1
  * <p>No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)</p>
  */
@jakarta.ws.rs.Path("/billing/subscriptions/addons")
@io.quarkiverse.openapi.generator.annotations.GeneratedClass(value="openapi.yaml", tag = "Billing")
@jakarta.enterprise.context.ApplicationScoped
public interface BillingApi {

     /**
     * Get all add-ons for a single company
     *
     * Returns the add-ons for a single company.
     *
     */
    @io.quarkiverse.openapi.generator.markers.OperationMarker(name="api_key", openApiSpecId="openapi_yaml", operationId="getCompanyAddons", method="GET", path="/v1/billing/subscriptions/addons")
    @io.quarkiverse.openapi.generator.markers.OperationMarker(name="oauth2", openApiSpecId="openapi_yaml", operationId="getCompanyAddons", method="GET", path="/v1/billing/subscriptions/addons")
    @jakarta.ws.rs.GET
    @jakarta.ws.rs.Produces({"application/json"})
    @io.quarkiverse.openapi.generator.annotations.GeneratedMethod("getCompanyAddons")
    public GetSubscriptionAddonsResponse getCompanyAddons(
    );

}