package dti.crmsis.back.clients.openapi.v1.api;

import java.util.List;
import java.util.Map;


import dti.crmsis.back.clients.openapi.v1.model.AddLeadLabelRequest;
import dti.crmsis.back.clients.openapi.v1.model.DeleteLeadIdResponse;
import dti.crmsis.back.clients.openapi.v1.model.GetLeadLabelsResponse;
import dti.crmsis.back.clients.openapi.v1.model.LeadNotFoundResponse;
import java.util.UUID;
import dti.crmsis.back.clients.openapi.v1.model.UpdateLeadLabelRequest;
import dti.crmsis.back.clients.openapi.v1.model.UpsertLeadLabelResponse;
/**
  * Pipedrive API v1
  * <p>No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)</p>
  */
@jakarta.ws.rs.Path("/leadLabels")
@io.quarkiverse.openapi.generator.annotations.GeneratedClass(value="openapi.yaml", tag = "LeadLabels")
@jakarta.enterprise.context.ApplicationScoped
public interface LeadLabelsApi {

     /**
     * Add a lead label
     *
     * Creates a lead label.
     *
     * @param addLeadLabelRequest 
     */
    @io.quarkiverse.openapi.generator.markers.OperationMarker(name="api_key", openApiSpecId="openapi_yaml", operationId="addLeadLabel", method="POST", path="/v1/leadLabels")
    @io.quarkiverse.openapi.generator.markers.OperationMarker(name="oauth2", openApiSpecId="openapi_yaml", operationId="addLeadLabel", method="POST", path="/v1/leadLabels")
    @jakarta.ws.rs.POST
    @jakarta.ws.rs.Consumes({"application/json"})
    @jakarta.ws.rs.Produces({"application/json"})
    @io.quarkiverse.openapi.generator.annotations.GeneratedMethod("addLeadLabel")
    public UpsertLeadLabelResponse addLeadLabel(
        AddLeadLabelRequest addLeadLabelRequest
    );

     /**
     * Delete a lead label
     *
     * Deletes a specific lead label.
     *
     * @param id The ID of the lead label
     */
    @io.quarkiverse.openapi.generator.markers.OperationMarker(name="api_key", openApiSpecId="openapi_yaml", operationId="deleteLeadLabel", method="DELETE", path="/v1/leadLabels/{id}")
    @io.quarkiverse.openapi.generator.markers.OperationMarker(name="oauth2", openApiSpecId="openapi_yaml", operationId="deleteLeadLabel", method="DELETE", path="/v1/leadLabels/{id}")
    @jakarta.ws.rs.DELETE
    @jakarta.ws.rs.Path("/{id}")
    @jakarta.ws.rs.Produces({"application/json"})
    @io.quarkiverse.openapi.generator.annotations.GeneratedMethod("deleteLeadLabel")
    public DeleteLeadIdResponse deleteLeadLabel(
        @io.quarkiverse.openapi.generator.annotations.GeneratedParam("id") @jakarta.ws.rs.PathParam("id")UUID id
    );

     /**
     * Get all lead labels
     *
     * Returns details of all lead labels. This endpoint does not support pagination and all labels are always returned.
     *
     */
    @io.quarkiverse.openapi.generator.markers.OperationMarker(name="api_key", openApiSpecId="openapi_yaml", operationId="getLeadLabels", method="GET", path="/v1/leadLabels")
    @io.quarkiverse.openapi.generator.markers.OperationMarker(name="oauth2", openApiSpecId="openapi_yaml", operationId="getLeadLabels", method="GET", path="/v1/leadLabels")
    @jakarta.ws.rs.GET
    @jakarta.ws.rs.Produces({"application/json"})
    @io.quarkiverse.openapi.generator.annotations.GeneratedMethod("getLeadLabels")
    public GetLeadLabelsResponse getLeadLabels(
    );

     /**
     * Update a lead label
     *
     * Updates one or more properties of a lead label. Only properties included in the request will be updated. 
     *
     * @param id The ID of the lead label
     * @param updateLeadLabelRequest 
     */
    @io.quarkiverse.openapi.generator.markers.OperationMarker(name="api_key", openApiSpecId="openapi_yaml", operationId="updateLeadLabel", method="PATCH", path="/v1/leadLabels/{id}")
    @io.quarkiverse.openapi.generator.markers.OperationMarker(name="oauth2", openApiSpecId="openapi_yaml", operationId="updateLeadLabel", method="PATCH", path="/v1/leadLabels/{id}")
    @jakarta.ws.rs.PATCH
    @jakarta.ws.rs.Path("/{id}")
    @jakarta.ws.rs.Consumes({"application/json"})
    @jakarta.ws.rs.Produces({"application/json"})
    @io.quarkiverse.openapi.generator.annotations.GeneratedMethod("updateLeadLabel")
    public UpsertLeadLabelResponse updateLeadLabel(
        @io.quarkiverse.openapi.generator.annotations.GeneratedParam("id") @jakarta.ws.rs.PathParam("id")UUID id, 
        UpdateLeadLabelRequest updateLeadLabelRequest
    );

}