package dti.crmsis.back.clients.openapi.v1.api;

import java.util.List;
import java.util.Map;


import dti.crmsis.back.clients.openapi.v1.model.GetPermissionSetResponse;
import dti.crmsis.back.clients.openapi.v1.model.GetPermissionSetsResponse;
import dti.crmsis.back.clients.openapi.v1.model.GetUserAssignmentsToPermissionSetResponse;
/**
  * Pipedrive API v1
  * <p>No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)</p>
  */
@jakarta.ws.rs.Path("/permissionSets")
@io.quarkiverse.openapi.generator.annotations.GeneratedClass(value="openapi.yaml", tag = "PermissionSets")
@jakarta.enterprise.context.ApplicationScoped
public interface PermissionSetsApi {

     /**
     * Get one permission set
     *
     * Returns data about a specific permission set.
     *
     * @param id The ID of the permission set
     */
    @io.quarkiverse.openapi.generator.markers.OperationMarker(name="api_key", openApiSpecId="openapi_yaml", operationId="getPermissionSet", method="GET", path="/v1/permissionSets/{id}")
    @io.quarkiverse.openapi.generator.markers.OperationMarker(name="oauth2", openApiSpecId="openapi_yaml", operationId="getPermissionSet", method="GET", path="/v1/permissionSets/{id}")
    @jakarta.ws.rs.GET
    @jakarta.ws.rs.Path("/{id}")
    @jakarta.ws.rs.Produces({"application/json"})
    @io.quarkiverse.openapi.generator.annotations.GeneratedMethod("getPermissionSet")
    public GetPermissionSetResponse getPermissionSet(
        @io.quarkiverse.openapi.generator.annotations.GeneratedParam("id") @jakarta.ws.rs.PathParam("id")String id
    );

     /**
     * List permission set assignments
     *
     * Returns the list of assignments for a permission set.
     *
     * @param id The ID of the permission set
     * @param start Pagination start
     * @param limit Items shown per page
     */
    @io.quarkiverse.openapi.generator.markers.OperationMarker(name="api_key", openApiSpecId="openapi_yaml", operationId="getPermissionSetAssignments", method="GET", path="/v1/permissionSets/{id}/assignments")
    @io.quarkiverse.openapi.generator.markers.OperationMarker(name="oauth2", openApiSpecId="openapi_yaml", operationId="getPermissionSetAssignments", method="GET", path="/v1/permissionSets/{id}/assignments")
    @jakarta.ws.rs.GET
    @jakarta.ws.rs.Path("/{id}/assignments")
    @jakarta.ws.rs.Produces({"application/json"})
    @io.quarkiverse.openapi.generator.annotations.GeneratedMethod("getPermissionSetAssignments")
    public GetUserAssignmentsToPermissionSetResponse getPermissionSetAssignments(
        @io.quarkiverse.openapi.generator.annotations.GeneratedParam("id") @jakarta.ws.rs.PathParam("id")String id, 
        @io.quarkiverse.openapi.generator.annotations.GeneratedParam("start") @jakarta.ws.rs.QueryParam("start") Integer start, 
        @io.quarkiverse.openapi.generator.annotations.GeneratedParam("limit") @jakarta.ws.rs.QueryParam("limit") Integer limit
    );

     /**
     * Get all permission sets
     *
     * Returns data about all permission sets.
     *
     * @param app The app to filter the permission sets by
     */
    @io.quarkiverse.openapi.generator.markers.OperationMarker(name="api_key", openApiSpecId="openapi_yaml", operationId="getPermissionSets", method="GET", path="/v1/permissionSets")
    @io.quarkiverse.openapi.generator.markers.OperationMarker(name="oauth2", openApiSpecId="openapi_yaml", operationId="getPermissionSets", method="GET", path="/v1/permissionSets")
    @jakarta.ws.rs.GET
    @jakarta.ws.rs.Produces({"application/json"})
    @io.quarkiverse.openapi.generator.annotations.GeneratedMethod("getPermissionSets")
    public GetPermissionSetsResponse getPermissionSets(
        @io.quarkiverse.openapi.generator.annotations.GeneratedParam("app") @jakarta.ws.rs.QueryParam("app") String app
    );

}