package dti.crmsis.back.clients.openapi.v1.api;

import java.util.List;
import java.util.Map;


import dti.crmsis.back.clients.openapi.v1.model.GetUserConnectionsResponse;
import dti.crmsis.back.clients.openapi.v1.model.UnathorizedResponse;
/**
  * Pipedrive API v1
  * <p>No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)</p>
  */
@jakarta.ws.rs.Path("/userConnections")
@io.quarkiverse.openapi.generator.annotations.GeneratedClass(value="openapi.yaml", tag = "UserConnections")
@jakarta.enterprise.context.ApplicationScoped
public interface UserConnectionsApi {

     /**
     * Get all user connections
     *
     * Returns data about all connections for the authorized user.
     *
     */
    @io.quarkiverse.openapi.generator.markers.OperationMarker(name="api_key", openApiSpecId="openapi_yaml", operationId="getUserConnections", method="GET", path="/v1/userConnections")
    @io.quarkiverse.openapi.generator.markers.OperationMarker(name="oauth2", openApiSpecId="openapi_yaml", operationId="getUserConnections", method="GET", path="/v1/userConnections")
    @jakarta.ws.rs.GET
    @jakarta.ws.rs.Produces({"application/json"})
    @io.quarkiverse.openapi.generator.annotations.GeneratedMethod("getUserConnections")
    public GetUserConnectionsResponse getUserConnections(
    );

}