USE CRMSIS;

CREATE TABLE RAW_REQUESTS
(
    ID            BIGINT AUTO_INCREMENT PRIMARY KEY,
    CUSTOMER_NAME CHAR(50),
    REQUEST_DATA  MEDIUMTEXT  NOT NULL,
#     STATUS        VARCHAR(50) NOT NULL DEFAULT 'PENDING',
    CREATED_AT    DATETIME    NOT NULL DEFAULT CURRENT_TIMESTAMP
#   ,  PROCESSED_AT DATETIME             DEFAULT NULL ON UPDATE CURRENT_TIMESTAMP
);

ALTER TABLE RAW_REQUESTS
    AUTO_INCREMENT = 1;
