version: '3.8'

services:
  crmsis-webhooks-nginx:
    image: nginx:latest
    container_name: crmsis_webhooks_nginx
    ports:
      - "80:80"
    volumes:
      - D:\projects\crmsis-1\config\crmsis-webhooks-nginx:/etc/nginx/
    networks:
      - common_network
    depends_on:
      - crmsis-webhooks-app

  crmsis-webhooks-app:
    image: ivandrozda/dti-crmsis-back-webhooks-v1:latest
    container_name: crmsis_webhooks_app
    environment:
      - QUARKUS_DATASOURCE_DB_KIND=mysql
      - QUARKUS_DATASOURCE_USERNAME=crmsis_usr
      - QUARKUS_DATASOURCE_PASSWORD=password
      - QUARKUS_DATASOURCE_JDBC_URL=JDBC:MYSQL://crmsis_webhooks_mysql:3306/CRMSIS
      - QUARKUS_HIBERNATE-ORM_DATABASE_GENERATION=none
      - QUARKUS_HTTP_PORT=8080
      - QUARKUS_LOG_CONSOLE_DARKEN=10
      - QUARKUS_INFO_ENABLED = TRUE
      - QUARKUS_MICROMETER_EXPORT_PROMETHEUS_ENABLED=true
      - QUARKUS_MICROMETER_EXPORT_PROMETHEUS_PATH=/metrics
      - MP_METRICS_ENABLED=true
    networks:
      - common_network
    depends_on:
      - crmsis-webhooks-mysql

  crmsis-webhooks-mysql:
    image: mysql:8.0
    container_name: crmsis_webhooks_mysql
    environment:
      MYSQL_ROOT_PASSWORD: secret
      MYSQL_DATABASE: CRMSIS
      MYSQL_USER: crmsis_usr
      MYSQL_PASSWORD: password
      MYSQL_ALLOW_EMPTY_PASSWORD: yes
    networks:
      - common_network
    volumes:
      - D:\projects\crmsis-1\config\crmsis-webhook-mysql-init.sql:/docker-entrypoint-initdb.d/init.sql
    #      - /mnt/volume_5g/mysql:/var/lib/mysql
    ports:
      - "3306:3306"

networks:
  common_network:
    driver: bridge