CREATE DATABASE SB_CLIENTS_BACK;-- remove this when switching to second node
GRANT ALL PRIVILEGES ON SB_CLIENTS_BACK.* TO 'sb_usr'@'%';

USE SB_APP;

CREATE TABLE RAW_REQUESTS
(
    ID           BIGINT AUTO_INCREMENT PRIMARY KEY,
    URL_PATH     CHAR(50),
    REQUEST_DATA MEDIUMTEXT NOT NULL,
    CREATED_AT   DATETIME   NOT NULL DEFAULT CURRENT_TIMESTAMP,
    INDEX IDX_CUSTOMER_NAME (URL_PATH)
);

ALTER TABLE RAW_REQUESTS
    AUTO_INCREMENT = 1;


CREATE TABLE IF NOT EXISTS CUSTOMERS
(
    ID            BIGINT AUTO_INCREMENT PRIMARY KEY,
    URL           TEXT     NOT NULL,
    FULL_NAME     TEXT     NOT NULL,
    URL_PATH      CHAR(50),
    CREATED_AT    DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    API_TOKEN     TEXT     NOT NULL,
    DELETED       DATETIME
    );

ALTER TABLE CUSTOMERS
    AUTO_INCREMENT = 1;

